[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "warthog"
requires-python = ">=3.10"
description = "A deep learning library built from scratch in Python and Rust"
readme = "README.md"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy"]

[tool.maturin]
python-source = "python"
module-name = "warthog._warthog"
features = ["pyo3/extension-module"]
exclude = [
    "**/__pycache__",
    "**/*.pyc",
    "**/*.pyo"
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
